### ISSUE TITLE
Tidy up `implementations`, `semver.yaml` and associated code.

### ISSUE THREAD

**Issue by mds1** [ethereum-optimism/superchain-registry#164] opened 2024-04-04 19:40 UTC
> Per superchain a set of canonical implementation deployments, per semver version, is tracked.
As default, an empty collection of deployments can be set:

I think this should be tweaked to clarify that it's the "governance approved standard implementations starting from `op-contracts/v1.3.0` and later" (i.e. MCP and later and only applies to standard + premier chains). In which case I agree with the `/superchain/implementations @ethereum-optimism/security-reviewers` assignment

_Originally posted by @mds1 in https://github.com/ethereum-optimism/superchain-registry/pull/163#discussion_r1552187127_
            

---

Update: we have no implemented an entirely new way of checking contract versions. 

This ticket now covers removing cruft from the old way of doing it, as well as other files which are only referenced in the deprecated `op-upgrade` package (which also needs to be removed).

**Comment by geoknee** [comment] 2024-06-26 12:10
This could be considered a duplicate of #289

**Comment by geoknee** [comment] 2024-07-02 14:14
In favour of #331

**Closed by geoknee** 2024-07-02 14:14 UTC
